config/routes.rb
Temptd::Application.routes.draw do

  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  resources :events
  resources :timeslots do
    resources :votes
  end

  root :to => 'events#current'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :event_type
  
  has_many :votes
  has_many :timeslots, dependent: :destroy
  accepts_nested_attributes_for :timeslots, reject_if: -> attr { attr['started_at'].blank? }, allow_destroy: true

  validates_presence_of :event_type

  attr_accessible :timeslots

  def to_s
    "#{event_type}"
  end

  def starts_at
    timeslots.order(:starts_at).first.starts_at
  end

  def calculate_event_details
    calculate_event_time
  end
  
  def winning_timeslot
    @winning_timeslot ||= timeslots.sort_by{|a| a.votes.size }.last
    return @winning_timeslot
  end

  # Return time of the most popular Timeslot
  def calculate_event_time
    return [winning_timeslot.starts_at, winning_timeslot.ends_at] if winning_timeslot
  end
  
  
  
  # 5.times do |day_index|
  #   day = monday + day_index.days
  #   2.times do |i|
  #     start_time = day + (17 + i * 2).hours 
  #     end_time = day + (19 + i * 2).hours 
  # 
  #     Timeslot.create(event_id: test_event.id, starts_at: start_time, ends_at: end_time)
  #   end
  # end
  
  
  def self.start_new_sports_event
    # Event.
  end
  
  def self.finish_current_sports_event
    
  end
  
end

app/models/event_preference.rb
class EventPreference < ActiveRecord::Base
  attr_accessible :category, :event_type_id
end

app/models/event_preferences.rb
class EventPreferences < ActiveRecord::Base
  attr_accessible :category, :event_type_id
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  attr_accessible :name

  def to_s
    return "#{name}"
  end
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  attr_accessible :event_id, :ends_at, :starts_at
  
  belongs_to :event
  has_many :votes, dependent: :destroy
  
  validates_presence_of :event_id, :starts_at
  
  def to_s
    range = starts_at.to_s
    range << " - #{ends_at}" if ends_at
    return range
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :nickname, :provider, :uid

  def to_s
    username
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.email    = auth.info.email
      user.username = auth.info.nickname
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/models/user_event_preference.rb
class UserEventPreference < ActiveRecord::Base
  attr_accessible :event_preference_id, :user_id, :value
end

app/models/user_event_preferences.rb
class UserEventPreferences < ActiveRecord::Base
  attr_accessible :event_preference_id, :user_id, :value
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :event_id, :timeslot_id, :user_id, :user, :timeslot, :event
  
  belongs_to :user
  belongs_to :event
  belongs_to :timeslot
  
  validates_presence_of :timeslot
  validates_presence_of :user
  validates_uniqueness_of :timeslot_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def current
    @event = Event.last
    
    if @event
      render action: :show, id: @event.id
    else
      redirect_to action: :new
    end
  end


  def index
    @events = Event.all
  end


  def show
    @event = Event.find(params[:id])
  end


  def new
    @event = Event.new
  end


  def edit
    @event = Event.find(params[:id])
  end


  def create
    @event = Event.new(params[:event])

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: "new"
    end
  end


  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: "edit"
    end
  end


  def destroy
    Event.find(params[:id]).destroy
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    
    if user.persisted?
      flash[:notice] = "Welcome to TempTD, home of TempTD"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :github, :all
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    
    
    debugger
  #  You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    timeslot = Timeslot.find(params[:timeslot_id])
    @vote = timeslot.votes.new(user: current_user, event: timeslot.event)
    
    if @vote.save
      redirect_to @vote.event, notice: 'Thanks for voting!'
    else
      redirect_to @vote.event, notice: 'Dang, your vote didn\'t work :('
    end
  end


  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    redirect_to @vote.event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_winning_time(event)
    if event.winning_timeslot
      event.winning_timeslot.to_s
    else
      "None"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= content_tag :button, :type => :submit, :class => "btn" do %>
       <i class="icon-plus-sign-alt"></i>
       Create Event
    <% end %>

<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class="table">
  <tr>
    <th>Type</th>
    <th>Votes</th>
    <th>Winning Time</th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event, event %></td>
      <td><%= event.votes.size %></td>
      <td><%= display_winning_time(event) %></td>
      <td>
        <%#= link_to 'Vote', event %>
        <%#= link_to 'Edit', edit_event_path(event) %>
        <%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<button class="btn">
  <i class="icon-caret-left"></i>
  <%= link_to 'Back', events_path %>
</button>

app/views/events/show.html.erb
<h1><%= @event %></h1>
<h2><%= @event.starts_at %></h2>

<% if current_user.blank? %>
  <h3>Login to rock the vote!</h3>
<% end %>

<% if @event.timeslots.empty? %>
  No timeslots!
<% else %>
  <ul class="timeslots">
    <% @event.timeslots.each do |timeslot| %>
      <%# TODO: Determine li class based on if current user has voted for that day  %>
      <li>
        <% if current_user %>
          <% if vote = current_user.votes.find_by_timeslot_id(timeslot.id) %>
            <%= timeslot %>
            <%= link_to "[Unvote]", timeslot_vote_path(timeslot, vote), confirm: "You sure you want to unvote that?", method: 'delete' %>
          <% else %>
            <%= link_to timeslot, {controller: :votes, timeslot_id: timeslot.id}, method: 'post' %>
          <% end %>
        <% else %>
          <%= timeslot %>
        <% end %>
        Votes: <%= timeslot.votes.count %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "TempTD", root_path, :class => 'brand' %>

<nav class="nav pull-right btn-group">
  <% if user_signed_in? %>
      <button class="btn"><%= link_to current_user, edit_user_registration_path %></button>
      <button class="btn"><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></button>
  <% else %>
      <button class="btn">
        <i class="icon-github-alt"></i>
        <%= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %>
      </button>
      <button class="btn">
        <i class="icon-plus-sign-alt"></i>
        <%= link_to('Sign up', new_user_registration_path) %>
      </button>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Temptd</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>              
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :timeslot_id %><br />
    <%= f.number_field :timeslot_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Timeslot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.user_id %></td>
    <td><%= vote.event %></td>
    <td><%= vote.timeslot_id %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @vote.user_id %>
</p>

<p>
  <b>Event:</b>
  <%= @vote.event %>
</p>

<p>
  <b>Timeslot:</b>
  <%= @vote.timeslot_id %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>